import cocos
import pyglet
import random
import cocos
import time
import sys
import os
from pyglet.gl import *
from pyglet.gl.glu import *
from cocos.director import director

__all__ = ['Backgrounds', 'Sounds', 'Cameras']

Backgrounds = {"office" : {"0" : pyglet.image.load("images\\office\\0.png"),
                           "1" : pyglet.image.load("images\\office\\1.png"),
                           "2" : pyglet.image.load("images\\office\\2.png"),
                           "r" : pyglet.image.load("images\\office\\r.png"),
                           "c" : pyglet.image.load("images\\office\\c.png")},
               "camera" : {"cam1a" : {"0" : pyglet.image.load("images\\cameras\\cam1a\\0.png"),
                                      "b" : pyglet.image.load("images\\cameras\\cam1a\\b.png"),
                                      "b-1" : pyglet.image.load("images\\cameras\\cam1a\\b-1.png"),
                                      "bc" : pyglet.image.load("images\\cameras\\cam1a\\bc.png"),
                                      "br" : pyglet.image.load("images\\cameras\\cam1a\\br.png"),
                                      "brc" : pyglet.image.load("images\\cameras\\cam1a\\brc.png"),
                                      "brc-1" : pyglet.image.load("images\\cameras\\cam1a\\brc-1.png")},
                           "cam1b" : {"0" : pyglet.image.load("images\\cameras\\cam1b\\0.png"),
                                      "b" : pyglet.image.load("images\\cameras\\cam1b\\b.png"),
                                      "c" : pyglet.image.load("images\\cameras\\cam1b\\c.png"),
                                      "c-1" : pyglet.image.load("images\\cameras\\cam1b\\c-1.png"),
                                      "r" : pyglet.image.load("images\\cameras\\cam1b\\r.png"),
                                      "r-1" : pyglet.image.load("images\\cameras\\cam1b\\r-1.png")},
                           "cam1c" : {"0" : pyglet.image.load("images\\cameras\\cam1c\\0.png"),
                                      "1" : pyglet.image.load("images\\cameras\\cam1c\\1.png"),
                                      "2" : pyglet.image.load("images\\cameras\\cam1c\\2.png"),
                                      "3" : pyglet.image.load("images\\cameras\\cam1c\\3.png"),
                                      "4" : pyglet.image.load("images\\cameras\\cam1c\\4.png"),
                                      "5" : pyglet.image.load("images\\cameras\\cam1c\\5.png")},
                           "cam2a" : {"0" : pyglet.image.load("images\\cameras\\cam2a\\0.png"),
                                      "1" : pyglet.image.load("images\\cameras\\cam2a\\1.png"),
                                      "r" : pyglet.image.load("images\\cameras\\cam2a\\1.png")},
                           "cam2b" : {"0" : pyglet.image.load("images\\cameras\\cam2b\\0.png"),
                                      "1" : pyglet.image.load("images\\cameras\\cam2b\\1.png"),
                                      "2" : pyglet.image.load("images\\cameras\\cam2b\\2.png"),
                                      "r" : pyglet.image.load("images\\cameras\\cam2b\\r.png"),
                                      "r-1" : pyglet.image.load("images\\cameras\\cam2b\\r-1.png")},
                           "cam3" : {"0" : pyglet.image.load("images\\cameras\\cam3\\0.png"),
                                     "r" : pyglet.image.load("images\\cameras\\cam3\\r.png")},
                           "cam4a" : {"0" : pyglet.image.load("images\\cameras\\cam4a\\0.png"),
                                      "1" : pyglet.image.load("images\\cameras\\cam4a\\1.png"),
                                      "2" : pyglet.image.load("images\\cameras\\cam4a\\2.png"),
                                      "b" : pyglet.image.load("images\\cameras\\cam4a\\b.png"),
                                      "c" : pyglet.image.load("images\\cameras\\cam4a\\c.png"),
                                      "c-1" : pyglet.image.load("images\\cameras\\cam4a\\c-1.png")},
                           "cam4b" : {"0" : pyglet.image.load("images\\cameras\\cam4b\\0.png"),
                                      "1" : pyglet.image.load("images\\cameras\\cam4b\\1.png"),
                                      "2" : pyglet.image.load("images\\cameras\\cam4b\\2.png"),
                                      "3" : pyglet.image.load("images\\cameras\\cam4b\\3.png"),
                                      "4" : pyglet.image.load("images\\cameras\\cam4b\\4.png"),
                                      "b" : pyglet.image.load("images\\cameras\\cam4b\\b.png"),
                                      "c" : pyglet.image.load("images\\cameras\\cam4b\\c.png"),
                                      "c-1" : pyglet.image.load("images\\cameras\\cam4b\\c-1.png"),
                                      "c-2" : pyglet.image.load("images\\cameras\\cam4b\\c-2.png")},
                           "cam5" : {"0" : pyglet.image.load("images\\cameras\\cam5\\0.png"),
                                     "1" : pyglet.image.load("images\\cameras\\cam5\\1.png"),
                                     "r" : pyglet.image.load("images\\cameras\\cam5\\r.png"),
                                     "r-1" : pyglet.image.load("images\\cameras\\cam5\\r-1.png")},
                           "cam6" : {"0" : pyglet.image.load("images\\cameras\\misc\\black.png")},
                           "cam7" : {"0" : pyglet.image.load("images\\cameras\\cam7\\0.png"),
                                     "b" : pyglet.image.load("images\\cameras\\cam7\\b.png"),
                                     "c" : pyglet.image.load("images\\cameras\\cam7\\c.png"),
                                     "c-1" : pyglet.image.load("images\\cameras\\cam7\\c-1.png")}},
               "powerout" : {"0" : pyglet.image.load("images\\office\\powerout\\0.png"),
                             "1" : pyglet.image.load("images\\office\\powerout\\1.png"),
                             "2" : pyglet.image.load("images\\office\\powerout\\2.png")}}

Sounds = {"ambience" : {"ambience" : pyglet.media.load("sounds\\ambience\\ambience.wav"),
                        "ambience2" : pyglet.media.load("sounds\\ambience\\ambience2.wav"),
                        "eerieambience" : pyglet.media.load("sounds\\ambience\\eerieambience.wav"),
                        "fan" : pyglet.media.load("sounds\\ambience\\fan.wav")},

          "camera" : {"blip" : pyglet.media.load("sounds\\camera\\blip.wav"),
                      "camerasound" : pyglet.media.load("sounds\\camera\\camerasound.wav"),
                      "camerasound2" : pyglet.media.load("sounds\\camera\\camerasound2.wav"),
                      "computernoise" : pyglet.media.load("sounds\\camera\\computernoise.wav"),
                      "deepsteps" : pyglet.media.load("sounds\\camera\\deepsteps.wav"),
                      "garble" : pyglet.media.load("sounds\\camera\\garble.wav"),
                      "garble2" : pyglet.media.load("sounds\\camera\\garble2.wav"),
                      "garble3" : pyglet.media.load("sounds\\camera\\garble3.wav"),
                      "piratesong" : pyglet.media.load("sounds\\camera\\piratesong.wav"),
                      "pots" : pyglet.media.load("sounds\\camera\\pots.wav"),
                      "pots2" : pyglet.media.load("sounds\\camera\\pots2.wav"),
                      "pots3" : pyglet.media.load("sounds\\camera\\pots3.wav"),
                      "pots4" : pyglet.media.load("sounds\\camera\\pots4.wav"),
                      "putdown" : pyglet.media.load("sounds\\camera\\putdown.wav"),
                      "run" : pyglet.media.load("sounds\\camera\\run.wav"),
                      "runningfast" : pyglet.media.load("sounds\\camera\\runningfast.wav"),
                      "static" : pyglet.media.load("sounds\\camera\\static.wav"),
                      "static2" : pyglet.media.load("sounds\\camera\\static2.wav")},

         "misc" : {"6AM" : pyglet.media.load("sounds\\misc\\6AM.wav"),
                   "children" : pyglet.media.load("sounds\\misc\\children.wav"),
                   "circus" : pyglet.media.load("sounds\\misc\\circus.wav"),
                   "door" : pyglet.media.load("sounds\\misc\\door.wav"),
                   "doorknocking" : pyglet.media.load("sounds\\misc\\doorknocking.wav"),
                   "doorpounding" : pyglet.media.load("sounds\\misc\\doorpounding.wav"),
                   "error" : pyglet.media.load("sounds\\misc\\error.wav"),
                   "honk" : pyglet.media.load("sounds\\misc\\honk.wav"),
                   "lighthum" : pyglet.media.load("sounds\\misc\\lighthum.wav"),
                   "musicbox" : pyglet.media.load("sounds\\misc\\musicbox.wav"),
                   "powerout" : pyglet.media.load("sounds\\misc\\powerout.wav"),
                   "robotvoice" : pyglet.media.load("sounds\\misc\\robotvoice.wav")},

         "scary" : {"breathing" : pyglet.media.load("sounds\\scary\\breathing.wav"),
                    "breathing2" : pyglet.media.load("sounds\\scary\\breathing2.wav"),
                    "breathing3" :    pyglet.media.load("sounds\\scary\\breathing3.wav"),
                    "breathing4" : pyglet.media.load("sounds\\scary\\breathing4.wav"),
                    "freddygiggle" : pyglet.media.load("sounds\\scary\\freddygiggle.wav"),
                    "freddygiggle2" : pyglet.media.load("sounds\\scary\\freddygiggle2.wav"),
                    "freddygiggle3" : pyglet.media.load("sounds\\scary\\freddygiggle3.wav"),
                    "giggle" : pyglet.media.load("sounds\\scary\\giggle.wav"),
                    "robotvoice" : pyglet.media.load("sounds\\scary\\robotvoice.wav"),
                    "windowscare" : pyglet.media.load("sounds\\scary\\windowscare.wav"),
                    "XSCREAM" : pyglet.media.load("sounds\\scary\\XSCREAM.wav"),
                    "XSCREAM2" : pyglet.media.load("sounds\\scary\\XSCREAM2.wav")}}
                    
Cameras = {"cam1a" : "",
           "cam1b" : "",
           "cam1c" : "",
           "cam2a" : "",
           "cam3" : "",
           "cam4a" : "",
           "cam4b" : "",
           "cam5" : "",
           "cam6" : "",
           "cam7" : ""}
